export const terms = [
  {
    id: "1",
    english: "girl",
    transcription: "[ɡɜːl]",
    russian: "девочка",
    tags: "general",
    tags_json: "['general']",
  },
  {
    id: "2",
    english: "road",
    transcription: "[rōd]",
    russian: "дорога",
    tags: "general",
    tags_json: "['general']",
  },
  {
    id: "3",
    english: "school",
    transcription: "[skuːl]",
    russian: "школа",
    tags: "general",
    tags_json: "['general']",
  },
  {
    id: "4",
    english: "hedgehog",
    transcription: "[ˈhedʒ(h)ɒɡ]",
    russian: "ёж",
    tags: "animal",
    tags_json: "['animal']",
  },
  {
    id: "5",
    english: "cat",
    transcription: "[cat]",
    russian: "кошка",
    tags: "animal",
    tags_json: "['animal']",
  },
  {
    id: "6",
    english: "dad",
    transcription: "[dæd]",
    russian: "папа",
    tags: "general",
    tags_json: "['general']",
  },
  {
    id: "7",
    english: "flower",
    transcription: "[ˈflaʊər]",
    russian: "цветок",
    tags: "nature",
    tags_json: "['nature']",
  },
  {
    id: "8",
    english: "word",
    transcription: "[wɜːrd]",
    russian: "слово",
    tags: "general",
    tags_json: "['general']",
  },
  {
    id: "9",
    english: "book",
    transcription: "[bʊk]",
    russian: "книга",
    tags: "general",
    tags_json: "['general']",
  },
  {
    id: "10",
    english: "chair",
    transcription: "[tʃer]",
    russian: "стул",
    tags: "general",
    tags_json: "['general']",
  },
  {
    id: "11",
    english: "apple",
    transcription: "[ˈæpl]",
    russian: "яблоко",
    tags: "food",
    tags_json: "['food']",
  },
  {
    id: "12",
    english: "milk",
    transcription: "[mɪlk]",
    russian: "молоко",
    tags: "food",
    tags_json: "['food']",
  },
  {
    id: "13",
    english: "bread",
    transcription: "[bred]",
    russian: "хлеб",
    tags: "food",
    tags_json: "['food']",
  },
  {
    id: "14",
    english: "tree",
    transcription: "[triː]",
    russian: "дерево",
    tags: "nature",
    tags_json: "['nature']",
  },
  {
    id: "15",
    english: "grass",
    transcription: "[ɡræs]",
    russian: "трава",
    tags: "nature",
    tags_json: "['nature']",
  },
  {
    id: "16",
    english: "watch",
    transcription: "[wɑːtʃ]",
    russian: "часы",
    tags: "general",
    tags_json: "['general']",
  },
  {
    id: "17",
    english: "wind",
    transcription: "[wɪnd]",
    russian: "ветер",
    tags: "nature",
    tags_json: "['nature']",
  },
  {
    id: "18",
    english: "rain",
    transcription: "[reɪn]",
    russian: "дождь",
    tags: "nature",
    tags_json: "['nature']",
  },
  {
    id: "19",
    english: "hare",
    transcription: "[her]",
    russian: "заяц",
    tags: "animal",
    tags_json: "['animal']",
  },
  {
    id: "20",
    english: "wheel",
    transcription: "[wiːl]",
    russian: "колесо",
    tags: "general",
    tags_json: "['general']",
  },
];
